"""Markdown report generation."""

from __future__ import annotations

from datetime import datetime, timezone

from robopsych.engine import DiagnosticEngine


def generate_report(engine: DiagnosticEngine, scenario_name: str = "") -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Robopsychological Diagnostic Report",
        "",
        f"**Date:** {now}",
        f"**Model:** `{engine.model}`",
        f"**Provider:** {engine.provider.name}",
    ]
    if scenario_name:
        lines.append(f"**Scenario:** {scenario_name}")
    lines.append(f"**Diagnostic steps:** {len(engine.steps)}")
    lines.append("")

    if engine.initial_response:
        lines.extend([
            "---",
            "",
            "## Initial Response (under diagnosis)",
            "",
            engine.initial_response,
            "",
        ])

    lines.extend(["---", ""])

    for i, step in enumerate(engine.steps, 1):
        lines.extend([
            f"## Step {i}: {step.prompt_id} — {step.prompt_name}",
            "",
            "<details>",
            f"<summary>Prompt sent</summary>",
            "",
            step.prompt_text.strip(),
            "",
            "</details>",
            "",
            "### Diagnosis",
            "",
            step.response,
            "",
            "---",
            "",
        ])

    lines.extend([
        f"*Generated by [robopsych](https://github.com/jrcruciani/robopsychology) v2.5.0*",
    ])
    return "\n".join(lines)
